version: 0.0
os: linux
files:
  - source: /index.js
    destination: /home/ec2-user/node-test 
file_exists_behavior: OVERWRITE
BeforeInstall:
  - location: /before_script.sh
    timeout: 300
    runas: root
ApplicationStop:
  - location: /after_script.sh
    timeout: 300
    runas: root
